version: '3'

services:
  app:
    build:
      context: .docker.local/app
    ports:
      - 22040:80
    volumes:
      - ./:/var/www/html
      - ./.docker.local/app/logs/nginx:/var/log/nginx
      - ./.docker.local/app/.composer:/root/.composer
    depends_on:
#      - mysql
      - postgres

#  mysql:
#    image: mysql:8.0
#    environment:
#      - MYSQL_DATABASE=laravel
#      - MYSQL_USER=mysql
#      - MYSQL_PASSWORD=secret
#      - MYSQL_ROOT_PASSWORD=secret
#    volumes:
#      - ./.docker.local/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
#      - ./.docker.local/mysql/data:/var/lib/mysql
#      - ./.docker.local/mysql/logs:/var/log/mysql
#    ports:
#      - 22042:3306

  postgres:
    build:
      context: .docker.local/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=laravel
    volumes:
      - ./.docker.local/postgres/data:/var/lib/postgresql/data
    ports:
      - 22041:5432

#  localstack:
#    image: localstack/localstack:latest
#    environment:
#      - SERVICES=s3
#      - DEFAULT_REGION=us-west-2
#      - DATA_DIR=/tmp/localstack/data
#    ports:
#      - 22042:4566
#    volumes:
#      - ./.docker.local/localstack/data:/tmp/localstack
#      - ./.docker.local/localstack/docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d
#    networks:
#      default:
#        aliases:
#          - laravel-bucket.localhost
